# Generated by Django 5.2 on 2025-04-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
