# Generated by Django 5.2 on 2025-04-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0003_users_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
